apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-storage-13-2-prod
  namespace: kuber-13-2-prod
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.45
    path: /mnt/nfs_prod