kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prod-storage
  namespace: kuber-13-2-prod
spec:
  storageClassName: "nfs"
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi